SELECT GU.USER_ID, GU.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD GB
INNER JOIN USED_GOODS_USER GU ON GB.WRITER_ID = GU.USER_ID
AND GB.STATUS = 'DONE'
GROUP BY GU.NICKNAME
HAVING(TOTAL_SALES) >= 700000
ORDER BY TOTAL_SALES;
